name: build macos and windows wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [macos-12, macosx_x86_64]
          - [macos-12, macosx_arm64]
          #- [macos-12, macosx_universal2]
          - [windows-2019, win_amd64]
        python-version: [cp310]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          ref: "v0.2.0"
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # NOTE: This is needed to ensure that hyperdrive-wrappers builds correctly.
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          version: nightly

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python dependencies
        run: python -m pip install --upgrade pip && python -m pip install --upgrade -r requirements-dev.txt

      - name: build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$HOME/.foundry/bin:$HOME/.cargo/env:$PATH" CARGO_TERM_COLOR="always"'
          CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$UserProfile\.foundry\bin;$UserProfile\.cargo\env;$PATH"'
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BEFORE_ALL_MACOS: >
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
            rustup show &&
            rustup target add aarch64-apple-darwin &&
            curl -L https://foundry.paradigm.xyz | sh &&
            foundryup
          CIBW_BUILD_VERBOSITY: 1
        with:
          output-dir: wheelhouse
          package-dir: crates/pyperdrive

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
