name: build wheels

on:
  push:
    branches:
      - main

jobs:
  detect-version-changes:
    uses: ./.github/workflows/check_version.yml
    with:
      file_path: crates/hyperdrivepy/pyproject.toml

  build-wheels-linux:
    needs: detect-version-changes
    # Run on main if version has changed
    if: needs.detect-version-changes.outputs.version_changed == 'true'
    name: build on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{github.token}}

      - name: set up pip
        run: python -m pip install --upgrade pip

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          ref: "v0.9.0"
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: build hyperdrivepy
        shell: bash
        run: source scripts/build_python.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: ./wheelhouse/*.whl
    
  build-wheels-cibw:
    needs: detect-version-changes
    # Run on main if version has changed
    if: needs.detect-version-changes.outputs.version_changed == 'true'
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, windows-2019]
        python-version: [cp310]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          ref: "v0.9.0"
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python dependencies
        run: python -m pip install --upgrade pip && python -m pip install --upgrade -r requirements-dev.txt
      
      - name: build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$HOME/.foundry/bin:$HOME/.cargo/env:$PATH" CARGO_TERM_COLOR="always"'
          CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$UserProfile\.foundry\bin;$UserProfile\.cargo\env;$PATH"'
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BEFORE_ALL_MACOS: >
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
            rustup show &&
            rustup target add aarch64-apple-darwin &&
            curl -L https://foundry.paradigm.xyz | sh &&
            foundryup
          CIBW_BUILD_VERBOSITY: 1
        with:
          output-dir: wheelhouse
          package-dir: crates/hyperdrivepy

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build-sdist:
    needs: detect-version-changes
    name: Build source distribution
    runs-on: ubuntu-latest
    # Run on main if version has changed
    if: needs.detect-version-changes.outputs.version_changed == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build crates/hyperdrivepy --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: crates/hyperdrivepy/dist/*.tar.gz

  upload_pypi:
    needs: [build-wheels-linux, build-wheels-cibw, build-sdist, detect-version-changes]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # Run on main if version has changed
    if: needs.detect-version-changes.outputs.version_changed == 'true'
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all wheels into dist/
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
