name: build linux wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    uses: ./.github/workflows/check-diff.yaml
    with:
      pattern: ^crates/pyperdrive/

  build:
    needs: detect-changes
    # Run only if changes are detected
    if: needs.detect-changes.outputs.changed == 'true'
    name: build on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          token: ${{github.token}}

      - name: set up pip
        run: python -m pip install --upgrade pip

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          ref: "v0.2.0"
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: build pyperdrive
        shell: bash
        run: source scripts/build_pyperdrive.sh

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
