name: build wheels

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  detect-version-changes:
    uses: ./.github/workflows/check_version.yml
    with:
      file_path: crates/hyperdrivepy/pyproject.toml

  linux:
    name: build linux
    # needs: detect-version-changes
    # runs-on: ubuntu-22.04
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # target: [x86_64, aarch64, armv7, s390x, ppc64le]
        target: [x86_64]
    #   defaults:
    #     run:
    #       working-directory: ./crates/hyperdrivepy
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: install python dependencies
        run: python -m pip install --upgrade pip && python -m pip install --upgrade -r ./requirements-dev.txt

      - name: setup foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: check out hyperdrive
        uses: actions/checkout@master
        with:
          repository: delvtech/hyperdrive
          ref: "v0.9.0"
          path: "./hyperdrive"
          ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist
          working-directory: crates/hyperdrivepy
          sccache: "true"
          manylinux: manylinux_2_31

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.target }}
          path: dist

  # windows:
  #   name: build windows
  #   # needs: detect-version-changes
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       target: [x64, x86]
  #   #   defaults:
  #   #     run:
  #   #       working-directory: .\crates\hyperdrivepy
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: setup python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.10"
  #         architecture: ${{ matrix.target }}

  #     - name: install python dependencies
  #       run: python -m pip install --upgrade pip && python -m pip install --upgrade -r ./requirements-dev.txt

  #     - name: check out hyperdrive
  #       uses: actions/checkout@master
  #       with:
  #         repository: delvtechhyperdrive
  #         ref: "v0.9.0"
  #         path: "./hyperdrive"
  #         ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

  #     - name: setup foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly

  #     - name: Build wheels
  #       uses: PyO3/maturin-action@v1
  #       with:
  #         target: ${{ matrix.target }}
  #         args: --release --out dist
  #         working-directory: crates/hyperdrivepy
  #         sccache: "true"

  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: wheels-windows-${{ matrix.target }}
  #         path: dist

  # macos:
  #   name: build macos
  #   # needs: detect-version-changes
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       target: [x86_64, aarch64]
  #   #   defaults:
  #   #     run:
  #   #       working-directory: ./crates/hyperdrivepy
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: setup python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.10"

  #     - name: install python dependencies
  #       run: python -m pip install --upgrade pip && python -m pip install --upgrade -r ./requirements-dev.txt

  #     - name: check out hyperdrive
  #       uses: actions/checkout@main
  #       with:
  #         repository: delvtech/hyperdrive
  #         ref: "v0.9.0"
  #         path: "./hyperdrive"
  #         ssh-key: ${{ secrets.HYPERDRIVE_ACCESS_KEY }}

  #     - name: setup foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly

  #     - name: Build wheels
  #       uses: PyO3/maturin-action@v1
  #       with:
  #         target: ${{ matrix.target }}
  #         args: --release --out dist
  #         working-directory: crates/hyperdrivepy
  #         sccache: "true"

  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: wheels-macos-${{ matrix.target }}
  #         path: dist

  sdist:
    name: sdist
    # needs: detect-version-changes
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./crates/hyperdrivepy
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: crates/hyperdrivepy

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: dist

  release:
    name: Release
    # needs: detect-version-changes
    runs-on: ubuntu-latest
    #   defaults:
    #     run:
    #       working-directory: ./crates/hyperdrivepy
    if: "startsWith(github.ref, 'refs/tags/')"
    # needs: [linux, windows, macos, sdist]
    needs: [linux]
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          working-directory: crates/hyperdrivepy
          command: upload
          args: --non-interactive --skip-existing wheels-*/*
