name: publish hyperwasm npm package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    # Only run this job if the release tag starts with "hyperwasm@v"
    if: startsWith(github.ref, 'refs/tags/hyperwasm@v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: cd crates/hyperwasm/pkg
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
